services:
  - type: web
    name: quiz4d-guardian-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      PYTHON_VERSION: 3.11.9
      PYTHONUNBUFFERED: "true"
